language: java
install:
- export main_repo_branch=$TRAVIS_BRANCH
- if [[ ${main_repo_branch} != "master" && ${main_repo_branch} != "development" ]]; then main_repo_branch=development ; fi
- echo "$main_repo_branch"
- git clone https://github.com/openworm/org.geppetto.model.git -b $main_repo_branch
- cd org.geppetto.model
- mvn install
- cd ..
env:
  global:
    secure: Si2gYwOlLp5rIfSPMV5Co02b8/b6SIBstdyjrUWbcaGGTkqGYGBHTEwkm997VV2WwN2Ev1ZtdWrEFrYxic0uhd1IfZoa/j4PA7mJjsySphK98Fpq6AxugJbkstm7GFtEswOjySzWXBATE14o5Ua8lNpIp/RLyQmwmLQ5M0OgXZM=
